name: CI

on: [push, pull_request]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Install node
        uses: actions/setup-node@v3

      - run: echo "화이팅 ${{github.actor}}!"
